### ISSUE TITLE
Can't install on Laravel 5.2

### ISSUE THREAD

**Issue by fagray** [Waavi/url-shortener#1]
Problem 1
    - waavi/url-shortener 1.0.1 requires mremi/url-shortener dev-master -> satisfiable by mremi/url-shortener[dev-master] but these conflict with your requirements or minimum-stability.
    - waavi/url-shortener 1.0 requires mremi/url-shortener dev-master -> satisfiable by mremi/url-shortener[dev-master] but these conflict with your requirements or minimum-stability.
    - Installation request for waavi/url-shortener 1.0.x -> satisfiable by waavi/url-shortener[1.0, 1.0.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by sildraug** [comment]
Fixed on 1.0.2

**Comment by AmirHome** [comment]
Do not Fixed

`$ composer require waavi/url-shortener 1.0.x
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing guzzle/guzzle (v3.8.1): Loading from cache
  - Installing mremi/url-shortener (v1.0.3): Loading from cache
  - Installing waavi/url-shortener (1.0.4): Loading from cache
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
`
